language: python
python:
  - "2.7"

services:
  - postgresql

install: 
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
  - python manage.py cov

after_success:
  - coveralls

